# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vf2plIQHXTtMRgbYYDL1kogtg615u8KL
"""

# train.py
import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

# 1. Load dataset
data = pd.read_csv("/content/Salary_Data.csv")

# 2. Pisahkan fitur dan target
X = data[['YearsExperience']]
y = data['Salary']

# 3. Split data train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Buat model
model = LinearRegression()
model.fit(X_train, y_train)

# 5. Evaluasi
y_pred = model.predict(X_test)
print("R2 Score:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

# 6. Simpan model
import os
if not os.path.exists("model"):
    os.makedirs("model")
pickle.dump(model, open("model/salary_model.pkl", "wb"))
print("Model berhasil disimpan ke model/salary_model.pkl")